### ISSUE TITLE
Feature request: Support for Windows Subsystem for Linux (wsl)

### ISSUE THREAD

**Issue by WToorenburghIntiveo** [ffaraone/vscode-opensslutils#1]
Hey there,

Thanks for making this extension! I'm a little wary to trust third-party binaries for OpenSSL, but with WSL, we can use the official ones! I tried setting `"opensslutils.opensslPath"` to `"wsl openssl"` ([following Microsoft documentation](https://docs.microsoft.com/en-us/windows/wsl/interop)) and it works, but paths are broken: 

```
Command failed: wsl openssl x509 -in /c:/ssl/key.pem -outform der -out \c:\ssl\key.der
Error opening Certificate /c:/ssl/key.pem
140471557162648:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/c:/ssl/key.pem','r')
140471557162648:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
```

I _think_ all that's needed for WSL to work is to have `/mnt/` added to the beginning of the path, and remove the colon (`:`) after the drive letter.

**Comment by ffaraone** [comment]
This features has been implemented in v1.1.1
